'''
Wrapper script for TMHMM, an ab-initio tool for identifying transmembrane alpha-helix proteins.

We will be using the protein fasta files generated by the Gene Prediction group.

For ease of post-processing the tool is being run to generate the output in the "short" format. 
'''

#!/usr/bin/env python

import subprocess,os,sys

def tmhmm_runner(input_directory_path,protein_file,output_directory_path):
	
	#Creating file path
	input_file=input_directory_path + protein_file

	#Creating a subdirectory in the output directory
	output_subdir=output_directory_path+"tmhmm/"
	
	#Creating output file
	mod_protein_file_name=protein_file.split("_")
	output_file=output_subdir+mod_protein_file_name[0]+"_tmhmm"

	#Checking if the subdirectory exists
	if not "tmhmm" in os.listdir(output_directory_path):
		os.mkdir(output_subdir)
	
	#Executing TMHMM
	'''
	The following commands produce the "short" output format for TMHMM.
	To get the "long" output format, edit the script 'tmhmm' in the directory /home/projects/group-b/tools/tmhmm-2.0c/bin/
	Make $opt_short = 0.
	To get the probability plots for each file, edit the same script to make $opt_plot=1
	
	'''
	try:
		print("Running TMHMM for "+protein_file)
		command = "tmhmm "+input_file+" > "+output_file
		os.system(command)
		#print(tmhmm_output)	
	except subprocess.CalledProcessError as err:
		print("Error running TMHMM. Check the input files")
		print("Error thrown: "+err.output)
		return False
	print("Completed running TMHMM")
	return True

def main():
	inputpath=sys.argv[1]
	outputpath=sys.argv[2]
	files=os.listdir(inputpath)
	if len(files) == 0:
                print("No files present in the directory.")
	for name in files:
		tmhmm=tmhmm_runner(inputpath,name,outputpath)
	
if __name__ == "__main__":
	main() 
	

	
	
